server:
  port: 8080


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/SocialMedia
    username: postgres
    password: asd123asd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update